### ISSUE TITLE
SSR Fails with: Unknown option: '--app'

### ISSUE THREAD

**Issue by CybrZr00** [chrisjwalk/angular-cli-netcore-ngrx-starter#1]
Hi,

I was doing the exact (almost, not material) same thing independently and came across yours whilst trying to fix the above error.
Unfortunately, it seems you get the same error when using SSR. I don't suppose you know how this can be fixed?  Google hasn't been my friend!  Here's the error:

> An unhandled exception occurred while processing the request.
> AggregateException: One or more errors occurred. (The NPM script 'build:ssr' exited without indicating success.
> Output was: 

> angular-cli-netcore-ngrx-starter@0.0.0 build:ssr G:\angular-cli-netcore-ngrx-starter-master\angular-cli-netcore-ngrx-starter-master\ClientApp
> npm run build -- --app=ssr --output-hashing=media "--watch"
>Error output was: Unknown option: '--app')
>System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
>InvalidOperationException: The NPM script 'build:ssr' exited without indicating success.
>Output was: 
> angular-cli-netcore-ngrx-starter@0.0.0 build:ssr G:\angular-cli-netcore-ngrx-starter-master\angular-cli-netcore-ngrx-starter-master\ClientApp
> npm run build -- --app=ssr --output-hashing=media "--watch"
>Error output was: Unknown option: '--app'

**Comment by chrisjwalk** [comment]
Hi Mark,

Thanks for getting in touch!

It looks like I updated to Angular 6 here without fully testing the SSR
option. This project was setup mostly as a code sample for a job, which I
got, so I haven't kept this repo 100% up to date. The problem here was the
upgrade didn't copy over the "ssr" project to the new angular.json file,
and the Angular CLI command line option has changed from "--app" to
"--project". I've fixed this here with this commit:

https://github.com/chrisjwalk/angular-cli-netcore-ngrx-starter/commit/067f02c1f4dedd0e89a195e20526c7ba3f09efc7

However, the SSR project still doesn't build. Looks like this may not be
fully supported with Angular 6 yet by looking at this PR / branch in
Microsoft's aspnet/templatingrepo:

https://github.com/aspnet/templating/pull/515
https://github.com/aspnet/templating/tree/kichalla/upgrade.angular.to.60/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/Angular-CSharp/ClientApp

Anyway, hope this gets you closer! Let me know if you figure it out.

Thanks,

-Chris

**Comment by chrisjwalk** [comment]
Sorry, I should have looked at that PR on MS's templating repo a bit better. Looks like my earlier fix didn't have the angular.json file setup correctly. I more or less merged the same changes [in this commit](https://github.com/chrisjwalk/angular-cli-netcore-ngrx-starter/commit/f94203c091ae5791b34e55690c577a6fb8f4a3cb) and it seems to run in SSR mode now. Please try pulling the latest and it should hopefully work for you now.

**Comment by CybrZr00** [comment]
Thats excellent @chrisjwalk I totally missed the PR! I can confirm all seems to be working, and checking the page source shows server rendering working properly! Thank you!
